# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Contestant.create(name: "Andrew Russel", entries: 4)
Contestant.create(name: "	Sean Robinson	", entries: 2)
Contestant.create(name:"Beca Mathieson", entries:	10)
Contestant.create(name:"Jack Pierce", entries:	1)
Contestant.create(name:"Connor McPherson", entries:	1)
Contestant.create(name:"Sarah Meyers", entries:	1)			
Contestant.create(name:"Matt Imhoff", entries:	1)
Contestant.create(name:"Jeremy Harlam", entries:	3)
Contestant.create(name:"Hunter Rush", entries:	5	)
Contestant.create(name:"Jess Gambino", entries:	2	)
Contestant.create(name:"Ryan Bower", entries:	1)
Contestant.create(name:"Gunnar Jaquez", entries:	1	)
Contestant.create(name:"Jurae Dilworth", entries:	1	)
Contestant.create(name:"Stephanie Meyers", entries:	1)
Contestant.create(name:"Max Rubin", entries:	2)
Contestant.create(name:"Joel Davies", entries:	1)
Contestant.create(name:"Julia Paley", entries:	4)
Contestant.create(name:"Rebecca Levities", entries:	2)
Contestant.create(name:"Conor Balkisson", entries:	4)
Contestant.create(name:"Laura and Martin Maccarty", entries: 20)
Contestant.create(name:"Annie Meany", entries:	2)
Contestant.create(name:"Nick Dolan", entries:	4)
Contestant.create(name:"Megan Millage", entries:	2)
Contestant.create(name:"Meghan Morin", entries:	4)
Contestant.create(name:"Cody Horn", entries:	3)
Contestant.create(name:"Lorelei Strasburger", entries:	7)
Contestant.create(name:"Suzie Halle", entries:	1)
Contestant.create(name:"Sara Birmingham", entries:	6)
Contestant.create(name:"Zach Heckendorf", entries:	1)
Contestant.create(name:"Jesus Gonzalez", entries:	2)
Contestant.create(name:"Maddie Goldman", entries:	5)
Contestant.create(name:"Ben Riopelle", entries:	3)
Contestant.create(name:"Adam Shockley", entries:	1)
Contestant.create(name:"Alex Sandberg", entries:	2)
Contestant.create(name:"Madeleing Halle", entries:	2)
Contestant.create(name:"Matt Weber", entries:	5)
Contestant.create(name:"Samantha Mock", entries:	4)
Contestant.create(name:"Sage Vogt", entries:	3)
Contestant.create(name:"Ryan C", entries:	4)
Contestant.create(name:"Ben Dohrmann", entries:	1)
Contestant.create(name:"Logan Banning", entries:	5	)
Contestant.create(name:"Lucas Raimondo", entries:	3	)
Contestant.create(name:"Stephen Petersilge", entries:	7)
Contestant.create(name:"Alex Obregon", entries:	3)
Contestant.create(name:"Caroline O'neill", entries:	5)
Contestant.create(name:"Jess Gurrentz", entries:	5)
Contestant.create(name:"Vic Fichman", entries:	11)
Contestant.create(name:"Gregory Harlam", entries:	10)
Contestant.create(name:"Elise Mackay", entries:	1)
Contestant.create(name:"Parker Connolly", entries:	1)
Contestant.create(name:"Ian Scobie", entries:	1)
Contestant.create(name:"Sean Woods", entries:	3)
Contestant.create(name:"Grace Coomaraswamy", entries:	1)
Contestant.create(name:"zhach Pham", entries:	1)
Contestant.create(name:"sam greason", entries:	11)
Contestant.create(name:"Daniel Lewis", entries:	1)
Contestant.create(name:"Chris Seahorn", entries:	1)
Contestant.create(name:"Joe Ryder", entries:	10)
Contestant.create(name:"Madde Burnham", entries:	1)
Contestant.create(name:"Brad Hale", entries:	5)
Contestant.create(name:"Lexi Gagliardi", entries:	2)
Contestant.create(name:"Tyler Allen", entries:	10)
Contestant.create(name:"Rob Jornayvaz", entries:	2)
Contestant.create(name:"Maddi Dunn", entries:	3)
